# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_header', models.CharField(max_length=50)),
                ('welcome_text', models.TextField(max_length=1500)),
                ('supply_header', models.CharField(max_length=50)),
                ('supply_text', models.TextField(max_length=1500)),
                ('our_service_header', models.CharField(max_length=50)),
                ('our_service_text', models.TextField(max_length=1500)),
            ],
        ),
    ]
